export const TEMPLATE_SELECT = "TEMPLATE_SELECT"


export const TEMPLATE_SELECT_REQUEST = "TEMPLATE_SELECT_REQUEST"
export const TEMPLATE_SELECT_SUCCESS = "TEMPLATE_SELECT_SUCCESS"
export const TEMPLATE_SELECT_FAILURE = "TEMPLATE_SELECT_FAILURE"
