export const TEMPLATE_FETCH_REQUEST = "TEMPLATE_FETCH_REQUEST"
export const TEMPLATE_FETCH_SUCCESS = "TEMPLATE_FETCH_SUCCESS"
export const TEMPLATE_FETCH_FAILURE = "TEMPLATE_FETCH_FAILURE"
export const TEMPLATE_FETCH_FULFILL = "TEMPLATE_FETCH_FULFILL"
export const TEMPLATE_CLEAR = "TEMPLATE_CLEAR"


export const CHART_DATA_POST_REQUEST = "CHART_DATA_POST_REQUEST"
export const CHART_DATA_POST_SUCCESS = "CHART_DATA_POST_SUCCESS"
export const CHART_DATA_POST_FAILURE = "CHART_DATA_POST_FAILURE"
export const CHART_DATA_CLEAR = "CHART_DATA_CLEAR"

export const CHART_META_POST_REQUEST = "CHART_META_POST_REQUEST"
export const CHART_META_POST_SUCCESS = "CHART_META_POST_SUCCESS"
export const CHART_META_POST_FAILURE = "CHART_META_POST_FAILURE"
export const CHART_META_CLEAR = "CHART_META_CLEAR"

export const CHART_CELL_EMPHASIZE = "CHART_CELL_EMPHASIZE"
export const CHART_CELL_EMPHASIZE_VALIDATE = "CHART_CELL_EMPHASIZE_VALIDATE"

export const CHART_COMMENT_POST_REQUEST = "CHART_COMMENT_POST_REQUEST"
export const CHART_COMMENT_POST_SUCCESS = "CHART_COMMENT_POST_SUCCESS"
export const CHART_COMMENT_POST_FAILURE = "CHART_COMMENT_POST_FAILURE"
export const CHART_COMMENT_VALIDATE = "CHART_COMMENT_VALIDATE"

export const DATA_MODAL_OPEN = "DATA_MODAL_OPEN"
export const DATA_MODAL_CLOSE = "DATA_MODAL_CLOSE"

export const DATA_PLAYER_SET = "DATA_PLAYER_SET"
export const DATA_PLAYER_CLEAR = "DATA_PLAYER_CLEAR"

export const MASK_SAVE = "MASK_SAVE"
export const MASK_CLEAR = "MASK_CLEAR"



export const COLOR_SAVE = "COLOR_SAVE"
export const COLOR_CLEAR = "COLOR_CLEAR"
export const THEME_SAVE = "THEME_SAVE"
export const THEME_CLEAR = "THEME_CLEAR"

export const APPEARANCE_PLAYER_SET = "APPEARANCE_PLAYER_SET"
export const APPEARANCE_PLAYER_CLEAR = "APPEARANCE_PLAYER_CLEAR"

export const GLOBAL_PLAYER_UPDATE = "GLOBAL_PLAYER_UPDATE"

export const PROCEDURE_CLEAR = "PROCEDURE_CLEAR"