export const TEMPLATES_THUMBNAILS_FETCH_REQUEST = "TEMPLATES_THUMBNAILS_FETCH_REQUEST"
export const TEMPLATES_THUMBNAILS_FETCH_SUCCESS = "TEMPLATES_THUMBNAILS_FETCH_SUCCESS"
export const TEMPLATES_THUMBNAILS_FETCH_FAILURE = "TEMPLATES_THUMBNAILS_FETCH_FAILURE"
export const TEMPLATES_THUMBNAILS_FETCH_FULFILL = "TEMPLATES_THUMBNAILS_FETCH_FULFILL"


export const TEMPLATES_FETCH_REQUEST = "TEMPLATES_FETCH_REQUEST"
export const TEMPLATES_FETCH_SUCCESS = "TEMPLATES_FETCH_SUCCESS"
export const TEMPLATES_FETCH_FAILURE = "TEMPLATES_FETCH_FAILURE"
export const TEMPLATES_FETCH_FULFILL = "TEMPLATES_FETCH_FULFILL"

export const INSTANCE_FETCH_REQUEST = "INSTANCE_FETCH_REQUEST"
export const INSTANCE_FETCH_SUCCESS = "INSTANCE_FETCH_SUCCESS"
export const INSTANCE_FETCH_FAILURE = "INSTANCE_FETCH_FAILURE"
export const INSTANCE_FETCH_FULFILL = "INSTANCE_FETCH_FULFILL"
